# Generated by Django 5.0 on 2025-03-07 00:13

import django_cpf_cnpj.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True),
        ),
    ]
