# Generated by Django 5.0 on 2025-03-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
