# Generated by Django 5.1.4 on 2025-01-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('Cs', 'Casa'), ('Apt', 'Apartamento'), ('Ch', 'Chalé'), ('St', 'Suíte')], max_length=3)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='imagens_casas/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_adicionais/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='bookings.casa')),
            ],
        ),
    ]
