# Generated by Django 5.0 on 2025-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='nome',
        ),
        migrations.AlterField(
            model_name='casa',
            name='capacidade_maxima',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='casa',
            name='contato',
            field=models.CharField(default='0', help_text='Digite o número de telefone com DDD', max_length=15),
        ),
    ]
