# Generated by Django 5.0 on 2025-03-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_casa_nome_alter_casa_capacidade_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='capacidade_maxima',
        ),
    ]
