# Generated by Django 5.1.7 on 2025-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_casa_capacidade_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='preco',
        ),
        migrations.AddField(
            model_name='casa',
            name='aceita_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='agua_inclusa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='ar_condicionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='area_de_lazer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='churrasqueira',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='energia_inclusa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='mobiliado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='numero_banheiros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='casa',
            name='numero_quartos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='casa',
            name='numero_suites',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='numero_vagas_garagem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='preco_mes',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AddField(
            model_name='casa',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='casa',
            name='wifi_incluido',
            field=models.BooleanField(default=False),
        ),
    ]
