# Generated by Django 5.1.4 on 2025-01-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_casa_capacidade_maxima_casa_disponivel_ate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='disponivel',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='disponivel_ate',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='disponivel_de',
        ),
    ]
