# Generated by Django 5.0 on 2025-03-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_casa_preco_casa_aceita_pets_casa_agua_inclusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='capacidade_máxima',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='casa',
            name='preco_mes',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
