# Generated by Django 5.1.6 on 2025-02-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_casa_disponivel_remove_casa_disponivel_ate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='preco_diaria',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='casa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='casa',
            name='linkcontato',
            field=models.URLField(default='https://exemplo.com'),
        ),
    ]
