# Generated by Django 5.1.6 on 2025-02-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_preco_diaria_casa_preco_remove_casa_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='linkcontato',
        ),
        migrations.AddField(
            model_name='casa',
            name='contato',
            field=models.CharField(default='https://exemplo.com', help_text='Digite o número de telefone com DDD, exemplo: 11991234567', max_length=15),
        ),
    ]
