# Generated by Django 5.0 on 2025-03-14 23:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_casa_capacidade_máxima_alter_casa_preco_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
