# Generated by Django 5.1.7 on 2025-03-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_casa_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='bookings.casa')),
            ],
        ),
    ]
