# Generated by Django 5.1.6 on 2025-02-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_casa_linkcontato_casa_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='contato',
            field=models.CharField(default='0', help_text='Digite o número de telefone com DDD, exemplo: 84991234567', max_length=15),
        ),
    ]
